services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cinema-ticket-app
    container_name: cinema_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cinema_ticket_management
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - cinema-network

  db:
    image: mysql:8.0
    container_name: cinema_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cinema_ticket_management
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - cinema_db_data:/var/lib/mysql
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  cinema_db_data:
